### ISSUE TITLE
中国和香港、台湾并列不太好吧

### ISSUE THREAD

**Issue by owldamon** [DesertsX/YuLeQuan_Stars_Relation_Graph_By_InteractiveGraph#1]
建议改成大陆， 不要犯原则错误啊

**Comment by DesertsX** [comment]
感谢你善意中肯的建议。我看了下当初的数据处理逻辑：“海外的地区一律用对应的国家名；中国的地区有细分的则一律用对应的省份名，无细分的则统一用“中国”；剩下的用“不详””。也就说是将大陆省份和港澳台等设为同级的，其他无细分地区数据项的则统一用“中国”。
